---
name: Reserved
description: Use the GitHub Discussions for questions, assistance, and discussions about this project.
labels: [pending-close]
body:
  - type: markdown
    attributes:
      value: |
        > [!IMPORTANT]
        > Do **not** open an issue.
        >
        > Use the [GitHub Discussions](https://github.com/tenthirtyam/community-vmware-desktop-hypervisor-mcp-server/discussions) for questions, assistance, and discussions about this project.
  - type: checkboxes
    attributes:
      label: Acknowledgement
      options:
        - label: "By submitting this issue, I affirm that I neglected to read the message above and can expect this item to be closed without review."
          required: true
